### PR TITLE
Donot change case

### PR DESCRIPTION
**Pull request by naokazuterada**
@jonasbn Hi, good evening from Japan.

I've implemented two features during this weekend. 
Could you check my English as usual? And please let me know if there are anything wired.

I always appreciate your kindness. Thank you.

CHANGES

- Add `remove_image` parameter. Ref: #43
- Add `lowercase` parameter. Ref: #40

### CODE REVIEW

**Comment by naokazuterada** [comment]
Hi, @jonasbn. Thank you a lot for your proposal. It's very helpful.

Please check it, and approve it if there are nothing else.

**Comment by naokazuterada** [comment]
@jonasbn Thank you!

**Comment by jonasbn** [comment]
Followed up with some primitive promotion https://twitter.com/jonasbn/status/912632340890968064

**Comment by naokazuterada** [comment]
@jonasbn Wow, thanks!

**Pull request merged**
