### PR TITLE
Allow regular expression in `id_replacement`

### PR DESCRIPTION
**Pull request by naokazuterada**
Hi @jonasbn , happy new year! 🌟 

I expanded an existing feature `id_replacements`.
Since this change includes a kind of breaking change, I am worried about how to announce it.
Could you take a look, and suggest me if you have better expression ideas, please?

Thanks.

### CODE REVIEW

**Comment by jonasbn** [comment]
Hi @naokazuterada 

And happy new year, I will have a look 👍

**Comment by jonasbn** [comment]
Hi @naokazuterada 

Been incredibly busy at work lately so I have not had much time to work on open source projects. Anyway not it is weekend and I could finally find the time to sit down and have a look at your changes.

As I understand your concern is the communication of the breaking changes. I had a look at [semver.org](https://semver.org/) and the the recommendation is to _bump_ the major part of the version number. 

Since the latest release is 2.7.0 and you have indicated this should be 2.8.0 and 3.0.0 is a scheduled future release you have to make a decision.

1. Should this release be renamed from 2.8.0 to 3.0.0, this would indicate the breaking change
1. Should the scheduled release 3.0.0 be renamed to 4.0.0, this requires some yak-shaving to get everything aligned, but might be worth the effort to get a clean and clear communication

In addition I thing we need to extend the documentation with a migration guide so users can go from 2.7.0 to 2.8.0 / 3.0.0 (depending on your decision).

I can write up a proposal for this, just need to wrap my head around the change coming with this release.

Let me know what you think,

jonasbn

**Comment by naokazuterada** [comment]
@jonasbn Hi, I'm so appreciate that you took a time for this project. 🙇 

As you mentioned, I'm also agree with the idea that we should bump the major version if there are breaking changes. So I close this PR.

My decision is to gather breaking changes into next release.

- Stop the release 2.8.0
- Modify 3.0.0 contents (put some issues away if it needs time and not includes breaking changes)
- Put changes of this PR to 3.0.0

It's my turn, I'm going to work on it.

> In addition I thing we need to extend the documentation with a migration guide so users can go from 2.7.0 to 2.8.0 / 3.0.0 (depending on your decision).
> 
> I can write up a proposal for this, just need to wrap my head around the change coming with this release.

Thank you very much! Migration guide is a nice idea! I will try to it too.

**Comment by jonasbn** [comment]
Hi @naokazuterada 

Just let me know if you need any reviews or other assistance - I will find the time to help out

jonasbn

**Pull request closed without merging**
