### PR TITLE
Tips section

### PR DESCRIPTION
**Pull request by jonasbn**
Hi @naokazuterada,

I finally found some time to evaluate issue #76 so I added a Tips section to the documentation and added my own issue #81 - please merge if you find the PR suitable.

And happy new year,

jonasbn

---
This change is [Reviewable](https://reviewable.io/reviews/naokazuterada/markdowntoc/82)

### CODE REVIEW

**Comment by naokazuterada** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 509 at r1](https://reviewable.io:443/reviews/naokazuterada/markdowntoc/82#-K_rL7PbNUacbDXnm8SL:-K_rL7PbNUacbDXnm8SM:b-9lnfkw) ([raw file](https://github.com/naokazuterada/markdowntoc/blob/f482dd1c8dcee0638077fcfe882405e875a8e46e/README.md#L509)):*
> ```Markdown
> ## Tips
> 
> ### How to remove the TOC
> ```

I think this title is little ambiguous. I couldn't imagine contents from this title at first. How is it to change it to `How to remove anchors which added by MarkdownTOC` or something like that?

---

*[README.md, line 511 at r1](https://reviewable.io:443/reviews/naokazuterada/markdowntoc/82#-K_rNGq1w0U_Bi3Pfr-l:-K_rNGq1w0U_Bi3Pfr-m:b689o9h) ([raw file](https://github.com/naokazuterada/markdowntoc/blob/f482dd1c8dcee0638077fcfe882405e875a8e46e/README.md#L511)):*
> ```Markdown
> ### How to remove the TOC
> 
> If you want to remove the TOC again, you do not have to go through your complete Markdown and remove all tags manually - just follow this simple guide.
> ```

You had better mention [this section](https://github.com/naokazuterada/MarkdownTOC#auto-anchoring-when-heading-has-anchor-defined). 
And hope to refer mutually.

---

*[README.md, line 524 at r1](https://reviewable.io:443/reviews/naokazuterada/markdowntoc/82#-K_rOOqrcheJyO1fKdd3:-K_rOOqrcheJyO1fKdd4:buc21zf) ([raw file](https://github.com/naokazuterada/markdowntoc/blob/f482dd1c8dcee0638077fcfe882405e875a8e46e/README.md#L524)):*
> ```Markdown
> 
> 
> 3. Now delete the TOC section from beginning to end and **MarkdownTOC** integration is gone
> ```

Please change this line to
```
<ol><li value="3">Now delete the TOC section from beginning to end and **MarkdownTOC** integration is gone</li></ol>
```
because the number of list is not collect. I hope README is optimized for display in HTML.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/naokazuterada/markdowntoc/82)*

**Comment by naokazuterada** [comment]
Hi, @jonasbn 

Thanks a lot for your thoughtfulness! Please consider my reviews on reviewable.

**Comment by jonasbn** [comment]
> <ol><li value="3">Now delete the TOC section from beginning to end and **MarkdownTOC** integration is gone</li></ol>

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 509 at r1](https://reviewable.io:443/reviews/naokazuterada/markdowntoc/82#-K_rL7PbNUacbDXnm8SL:-Ka2ye9R_jws3uidu5n-:b-tnt4ab) ([raw file](https://github.com/naokazuterada/markdowntoc/blob/f482dd1c8dcee0638077fcfe882405e875a8e46e/README.md#L509)):*
<details><summary><i>Previously, naokazuterada (Naokazu Terada) wrote…</i></summary><blockquote>

I think this title is little ambiguous. I couldn't imagine contents from this title at first. How is it to change it to `How to remove anchors which added by MarkdownTOC` or something like that?
</blockquote></details>

I have changed it a rephrased it a bit

---

*[README.md, line 511 at r1](https://reviewable.io:443/reviews/naokazuterada/markdowntoc/82#-K_rNGq1w0U_Bi3Pfr-l:-Ka2ymveNAmF7xNVcYWA:b-ragse3) ([raw file](https://github.com/naokazuterada/markdowntoc/blob/f482dd1c8dcee0638077fcfe882405e875a8e46e/README.md#L511)):*
<details><summary><i>Previously, naokazuterada (Naokazu Terada) wrote…</i></summary><blockquote>

You had better mention [this section](https://github.com/naokazuterada/MarkdownTOC#auto-anchoring-when-heading-has-anchor-defined). 
And hope to refer mutually.
</blockquote></details>

I have made references now in both sections

---

*[README.md, line 524 at r1](https://reviewable.io:443/reviews/naokazuterada/markdowntoc/82#-K_rOOqrcheJyO1fKdd3:-Ka2yqi7UE3LKiO3Rado:bsdwjlh) ([raw file](https://github.com/naokazuterada/markdowntoc/blob/f482dd1c8dcee0638077fcfe882405e875a8e46e/README.md#L524)):*
<details><summary><i>Previously, naokazuterada (Naokazu Terada) wrote…</i></summary><blockquote>

Please change this line to
```
<ol><li value="3">Now delete the TOC section from beginning to end and **MarkdownTOC** integration is gone</li></ol>
```
because the number of list is not collect. I hope README is optimized for display in HTML.
</blockquote></details>

Tried the HTML and it looks as if it renders correctly, at least on Github

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/naokazuterada/markdowntoc/82#-:-Ka2yXBFRo20LutWHkcB:bttpzab)*

**Comment by jonasbn** [comment]
Hi @naokazuterada,

Thanks for the feedback, I have tried to accommodate your review comments, please review again.

**Comment by naokazuterada** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/naokazuterada/markdowntoc/82)*

**Comment by naokazuterada** [comment]
@jonasbn Thank you very much! It's merged.

**Pull request merged**
