### PR TITLE
You might drop bs4 dependency

### PR DESCRIPTION
**Pull request by ziembla**
Thanks for a great tool!
The beautiful soup wouldn't work for me but I think you could easily drop that additional dependency by using one more regex - the only victim would be "id_replacements" (it'd need double-quotes inside), but they are not only impractical to set in the document even now but also should rather be set user-wide as json in the first place, shouldn't they?
All unit tests passing (thanks again - for having them built-in and for the guideline to use them).
Regards

### CODE REVIEW

**Comment by ziembla** [comment]
If I am reading logs correctly:
- "coveralls" complains that coverage dropped but I don't know exactly why, the fact is that the number of lines did change
- travis' problem "pip: command not found" doesn't seem to be my fault

**Comment by jonasbn** [comment]
@ziembla the increase in lines would explain the decrease in coverage, even if the number of lines covered it the same

**Comment by naokazuterada** [comment]
@ziembla Hi, thank you for your PR and sorry for my late reply. 😃 

I want to consider about removing bs because I think it will provide more useful functions in coming new features. So please tell me about your problem. I'm not sure why bs doesn't work your environment, is there any special stuff?

**Comment by ziembla** [comment]
@naokazuterada thanks, now it's me to reply after an even longer delay...
I needed to use the addon on the offline computer where the sublime couldn't reach internet to get dependencies (I just copy Packages folder there). 
I haven't found the easy way to install the package into sublime environment... And as I looked into your source and seen there was only one and simple to change place where bs was used I just did that.
If you plan to add some features that would need more of bs power to avoid implementing advanced processing by hand, perhaps you shouldn't care about my scenario.
On the other hand I am always a bit sceptical about addons installing their own dependencies as that may easily lead to conflicting version dependencies... (I didn't dig into sublime addon architecture but I don't expect they're isolated python envs?)
Regards

**Comment by naokazuterada** [comment]
@ziembla Hi, thank you for reply! Your case is unexpected for me, but make sense. Sorry I have no idea for dealing with it.

I've considered and decided to drop bs this time. I don't know whether I will revert it or not in the future, but, as you said, it's not necessary so far.

https://github.com/naokazuterada/MarkdownTOC/releases/tag/2.7.1

Thank you for your contribution again! 🏅

**Comment by ziembla** [comment]
Thanks a lot, I am switching back to your official repo then!

**Comment by naokazuterada** [comment]
BTW, I've fixed travis errors. It's come from travis updates.

**Pull request merged**
